FROM mhart/alpine-node:8.8

WORKDIR /usr/src/app

RUN mkdir -p /usr/src/app/dist
ADD . .
ADD .env.template .env
RUN apk add --no-cache python make g++ libc6-compat && \
    npm install && \
    npm run build && \
    rm -rf node_modules && \
    npm install --production && \
    apk del --purge python make g++

CMD npm run serve
